#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace group_project_i_brownie_bandits
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BaseballDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::group_project_i_brownie_bandits.Properties.Settings.Default.BaseballDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Allstar> Allstars
		{
			get
			{
				return this.GetTable<Allstar>();
			}
		}
		
		public System.Data.Linq.Table<SeriesPost> SeriesPosts
		{
			get
			{
				return this.GetTable<SeriesPost>();
			}
		}
		
		public System.Data.Linq.Table<Baseball_Teams> Baseball_Teams
		{
			get
			{
				return this.GetTable<Baseball_Teams>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Allstars")]
	public partial class Allstar
	{
		
		private string _playerID;
		
		private short _yearID;
		
		private byte _gameNum;
		
		private string _gameID;
		
		private string _teamID;
		
		private string _lgID;
		
		private System.Nullable<bool> _GP;
		
		private System.Nullable<byte> _startingPos;
		
		public Allstar()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_playerID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string playerID
		{
			get
			{
				return this._playerID;
			}
			set
			{
				if ((this._playerID != value))
				{
					this._playerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yearID", DbType="SmallInt NOT NULL")]
		public short yearID
		{
			get
			{
				return this._yearID;
			}
			set
			{
				if ((this._yearID != value))
				{
					this._yearID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameNum", DbType="TinyInt NOT NULL")]
		public byte gameNum
		{
			get
			{
				return this._gameNum;
			}
			set
			{
				if ((this._gameNum != value))
				{
					this._gameNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gameID", DbType="NVarChar(50)")]
		public string gameID
		{
			get
			{
				return this._gameID;
			}
			set
			{
				if ((this._gameID != value))
				{
					this._gameID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string teamID
		{
			get
			{
				return this._teamID;
			}
			set
			{
				if ((this._teamID != value))
				{
					this._teamID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lgID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lgID
		{
			get
			{
				return this._lgID;
			}
			set
			{
				if ((this._lgID != value))
				{
					this._lgID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GP", DbType="Bit")]
		public System.Nullable<bool> GP
		{
			get
			{
				return this._GP;
			}
			set
			{
				if ((this._GP != value))
				{
					this._GP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startingPos", DbType="TinyInt")]
		public System.Nullable<byte> startingPos
		{
			get
			{
				return this._startingPos;
			}
			set
			{
				if ((this._startingPos != value))
				{
					this._startingPos = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SeriesPost")]
	public partial class SeriesPost
	{
		
		private int _yearID;
		
		private string _round;
		
		private string _teamIDwinner;
		
		private string _lgIDwinner;
		
		private string _teamIDloser;
		
		private string _lgIDloser;
		
		private byte _wins;
		
		private byte _losses;
		
		private bool _ties;
		
		public SeriesPost()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yearID", DbType="Int NOT NULL")]
		public int yearID
		{
			get
			{
				return this._yearID;
			}
			set
			{
				if ((this._yearID != value))
				{
					this._yearID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_round", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string round
		{
			get
			{
				return this._round;
			}
			set
			{
				if ((this._round != value))
				{
					this._round = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamIDwinner", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string teamIDwinner
		{
			get
			{
				return this._teamIDwinner;
			}
			set
			{
				if ((this._teamIDwinner != value))
				{
					this._teamIDwinner = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lgIDwinner", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lgIDwinner
		{
			get
			{
				return this._lgIDwinner;
			}
			set
			{
				if ((this._lgIDwinner != value))
				{
					this._lgIDwinner = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamIDloser", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string teamIDloser
		{
			get
			{
				return this._teamIDloser;
			}
			set
			{
				if ((this._teamIDloser != value))
				{
					this._teamIDloser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lgIDloser", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lgIDloser
		{
			get
			{
				return this._lgIDloser;
			}
			set
			{
				if ((this._lgIDloser != value))
				{
					this._lgIDloser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wins", DbType="TinyInt NOT NULL")]
		public byte wins
		{
			get
			{
				return this._wins;
			}
			set
			{
				if ((this._wins != value))
				{
					this._wins = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_losses", DbType="TinyInt NOT NULL")]
		public byte losses
		{
			get
			{
				return this._losses;
			}
			set
			{
				if ((this._losses != value))
				{
					this._losses = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ties", DbType="Bit NOT NULL")]
		public bool ties
		{
			get
			{
				return this._ties;
			}
			set
			{
				if ((this._ties != value))
				{
					this._ties = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Teams")]
	public partial class Baseball_Teams
	{
		
		private int _yearID;
		
		private string _lgID;
		
		private string _teamID;
		
		private string _franchID;
		
		private string _divID;
		
		private int _Rank;
		
		private int _G;
		
		private string _Ghome;
		
		private int _W;
		
		private int _L;
		
		private string _DivWin;
		
		private string _WCWin;
		
		private System.Nullable<bool> _LgWin;
		
		private System.Nullable<bool> _WSWin;
		
		private int _R;
		
		private int _AB;
		
		private int _H;
		
		private int @__2B;
		
		private int @__3B;
		
		private int _HR;
		
		private int _BB;
		
		private System.Nullable<int> _SO;
		
		private System.Nullable<int> _SB;
		
		private System.Nullable<int> _CS;
		
		private string _HBP;
		
		private string _SF;
		
		private int _RA;
		
		private int _ER;
		
		private double _ERA;
		
		private int _CG;
		
		private int _SHO;
		
		private int _SV;
		
		private int _IPouts;
		
		private int _HA;
		
		private int _HRA;
		
		private int _BBA;
		
		private int _SOA;
		
		private int _E;
		
		private System.Nullable<int> _DP;
		
		private double _FP;
		
		private string _name;
		
		private string _park;
		
		private System.Nullable<int> _attendance;
		
		private int _BPF;
		
		private int _PPF;
		
		private string _teamIDBR;
		
		private string _teamIDlahman45;
		
		private string _teamIDretro;
		
		public Baseball_Teams()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yearID", DbType="Int NOT NULL")]
		public int yearID
		{
			get
			{
				return this._yearID;
			}
			set
			{
				if ((this._yearID != value))
				{
					this._yearID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lgID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lgID
		{
			get
			{
				return this._lgID;
			}
			set
			{
				if ((this._lgID != value))
				{
					this._lgID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string teamID
		{
			get
			{
				return this._teamID;
			}
			set
			{
				if ((this._teamID != value))
				{
					this._teamID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_franchID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string franchID
		{
			get
			{
				return this._franchID;
			}
			set
			{
				if ((this._franchID != value))
				{
					this._franchID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_divID", DbType="NVarChar(1)")]
		public string divID
		{
			get
			{
				return this._divID;
			}
			set
			{
				if ((this._divID != value))
				{
					this._divID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="Int NOT NULL")]
		public int Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this._Rank = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G", DbType="Int NOT NULL")]
		public int G
		{
			get
			{
				return this._G;
			}
			set
			{
				if ((this._G != value))
				{
					this._G = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghome", DbType="NVarChar(50)")]
		public string Ghome
		{
			get
			{
				return this._Ghome;
			}
			set
			{
				if ((this._Ghome != value))
				{
					this._Ghome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_W", DbType="Int NOT NULL")]
		public int W
		{
			get
			{
				return this._W;
			}
			set
			{
				if ((this._W != value))
				{
					this._W = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L", DbType="Int NOT NULL")]
		public int L
		{
			get
			{
				return this._L;
			}
			set
			{
				if ((this._L != value))
				{
					this._L = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DivWin", DbType="NVarChar(1)")]
		public string DivWin
		{
			get
			{
				return this._DivWin;
			}
			set
			{
				if ((this._DivWin != value))
				{
					this._DivWin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WCWin", DbType="NVarChar(1)")]
		public string WCWin
		{
			get
			{
				return this._WCWin;
			}
			set
			{
				if ((this._WCWin != value))
				{
					this._WCWin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LgWin", DbType="Bit")]
		public System.Nullable<bool> LgWin
		{
			get
			{
				return this._LgWin;
			}
			set
			{
				if ((this._LgWin != value))
				{
					this._LgWin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WSWin", DbType="Bit")]
		public System.Nullable<bool> WSWin
		{
			get
			{
				return this._WSWin;
			}
			set
			{
				if ((this._WSWin != value))
				{
					this._WSWin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="Int NOT NULL")]
		public int R
		{
			get
			{
				return this._R;
			}
			set
			{
				if ((this._R != value))
				{
					this._R = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AB", DbType="Int NOT NULL")]
		public int AB
		{
			get
			{
				return this._AB;
			}
			set
			{
				if ((this._AB != value))
				{
					this._AB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H", DbType="Int NOT NULL")]
		public int H
		{
			get
			{
				return this._H;
			}
			set
			{
				if ((this._H != value))
				{
					this._H = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_2B]", Storage="__2B", DbType="Int NOT NULL")]
		public int _2B
		{
			get
			{
				return this.@__2B;
			}
			set
			{
				if ((this.@__2B != value))
				{
					this.@__2B = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_3B]", Storage="__3B", DbType="Int NOT NULL")]
		public int _3B
		{
			get
			{
				return this.@__3B;
			}
			set
			{
				if ((this.@__3B != value))
				{
					this.@__3B = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HR", DbType="Int NOT NULL")]
		public int HR
		{
			get
			{
				return this._HR;
			}
			set
			{
				if ((this._HR != value))
				{
					this._HR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BB", DbType="Int NOT NULL")]
		public int BB
		{
			get
			{
				return this._BB;
			}
			set
			{
				if ((this._BB != value))
				{
					this._BB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO", DbType="Int")]
		public System.Nullable<int> SO
		{
			get
			{
				return this._SO;
			}
			set
			{
				if ((this._SO != value))
				{
					this._SO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SB", DbType="Int")]
		public System.Nullable<int> SB
		{
			get
			{
				return this._SB;
			}
			set
			{
				if ((this._SB != value))
				{
					this._SB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CS", DbType="Int")]
		public System.Nullable<int> CS
		{
			get
			{
				return this._CS;
			}
			set
			{
				if ((this._CS != value))
				{
					this._CS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HBP", DbType="NVarChar(50)")]
		public string HBP
		{
			get
			{
				return this._HBP;
			}
			set
			{
				if ((this._HBP != value))
				{
					this._HBP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SF", DbType="NVarChar(50)")]
		public string SF
		{
			get
			{
				return this._SF;
			}
			set
			{
				if ((this._SF != value))
				{
					this._SF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RA", DbType="Int NOT NULL")]
		public int RA
		{
			get
			{
				return this._RA;
			}
			set
			{
				if ((this._RA != value))
				{
					this._RA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ER", DbType="Int NOT NULL")]
		public int ER
		{
			get
			{
				return this._ER;
			}
			set
			{
				if ((this._ER != value))
				{
					this._ER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ERA", DbType="Float NOT NULL")]
		public double ERA
		{
			get
			{
				return this._ERA;
			}
			set
			{
				if ((this._ERA != value))
				{
					this._ERA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CG", DbType="Int NOT NULL")]
		public int CG
		{
			get
			{
				return this._CG;
			}
			set
			{
				if ((this._CG != value))
				{
					this._CG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHO", DbType="Int NOT NULL")]
		public int SHO
		{
			get
			{
				return this._SHO;
			}
			set
			{
				if ((this._SHO != value))
				{
					this._SHO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SV", DbType="Int NOT NULL")]
		public int SV
		{
			get
			{
				return this._SV;
			}
			set
			{
				if ((this._SV != value))
				{
					this._SV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPouts", DbType="Int NOT NULL")]
		public int IPouts
		{
			get
			{
				return this._IPouts;
			}
			set
			{
				if ((this._IPouts != value))
				{
					this._IPouts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HA", DbType="Int NOT NULL")]
		public int HA
		{
			get
			{
				return this._HA;
			}
			set
			{
				if ((this._HA != value))
				{
					this._HA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HRA", DbType="Int NOT NULL")]
		public int HRA
		{
			get
			{
				return this._HRA;
			}
			set
			{
				if ((this._HRA != value))
				{
					this._HRA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BBA", DbType="Int NOT NULL")]
		public int BBA
		{
			get
			{
				return this._BBA;
			}
			set
			{
				if ((this._BBA != value))
				{
					this._BBA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOA", DbType="Int NOT NULL")]
		public int SOA
		{
			get
			{
				return this._SOA;
			}
			set
			{
				if ((this._SOA != value))
				{
					this._SOA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E", DbType="Int NOT NULL")]
		public int E
		{
			get
			{
				return this._E;
			}
			set
			{
				if ((this._E != value))
				{
					this._E = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP", DbType="Int")]
		public System.Nullable<int> DP
		{
			get
			{
				return this._DP;
			}
			set
			{
				if ((this._DP != value))
				{
					this._DP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FP", DbType="Float NOT NULL")]
		public double FP
		{
			get
			{
				return this._FP;
			}
			set
			{
				if ((this._FP != value))
				{
					this._FP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_park", DbType="NVarChar(MAX)")]
		public string park
		{
			get
			{
				return this._park;
			}
			set
			{
				if ((this._park != value))
				{
					this._park = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attendance", DbType="Int")]
		public System.Nullable<int> attendance
		{
			get
			{
				return this._attendance;
			}
			set
			{
				if ((this._attendance != value))
				{
					this._attendance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BPF", DbType="Int NOT NULL")]
		public int BPF
		{
			get
			{
				return this._BPF;
			}
			set
			{
				if ((this._BPF != value))
				{
					this._BPF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PPF", DbType="Int NOT NULL")]
		public int PPF
		{
			get
			{
				return this._PPF;
			}
			set
			{
				if ((this._PPF != value))
				{
					this._PPF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamIDBR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string teamIDBR
		{
			get
			{
				return this._teamIDBR;
			}
			set
			{
				if ((this._teamIDBR != value))
				{
					this._teamIDBR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamIDlahman45", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string teamIDlahman45
		{
			get
			{
				return this._teamIDlahman45;
			}
			set
			{
				if ((this._teamIDlahman45 != value))
				{
					this._teamIDlahman45 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamIDretro", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string teamIDretro
		{
			get
			{
				return this._teamIDretro;
			}
			set
			{
				if ((this._teamIDretro != value))
				{
					this._teamIDretro = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
