#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace group_project_i_brownie_bandits
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SportsLeagues")]
	public partial class SoccerLeagueDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSoccerGame(SoccerGame instance);
    partial void UpdateSoccerGame(SoccerGame instance);
    partial void DeleteSoccerGame(SoccerGame instance);
    partial void InsertSoccerPlayer(SoccerPlayer instance);
    partial void UpdateSoccerPlayer(SoccerPlayer instance);
    partial void DeleteSoccerPlayer(SoccerPlayer instance);
    #endregion
		
		public SoccerLeagueDataContext() : 
				base(global::group_project_i_brownie_bandits.Properties.Settings.Default.SportsLeaguesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SoccerLeagueDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SoccerLeagueDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SoccerLeagueDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SoccerLeagueDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SoccerGame> SoccerGames
		{
			get
			{
				return this.GetTable<SoccerGame>();
			}
		}
		
		public System.Data.Linq.Table<SoccerPlayer> SoccerPlayers
		{
			get
			{
				return this.GetTable<SoccerPlayer>();
			}
		}
		
		public System.Data.Linq.Table<SoccerPlayersValuation> SoccerPlayersValuations
		{
			get
			{
				return this.GetTable<SoccerPlayersValuation>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SoccerGames")]
	public partial class SoccerGame : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _game_id;
		
		private string _competition_id;
		
		private int _season;
		
		private string _round;
		
		private System.DateTime _date;
		
		private System.Nullable<int> _home_club_id;
		
		private System.Nullable<int> _away_club_id;
		
		private System.Nullable<byte> _home_club_goals;
		
		private System.Nullable<byte> _away_club_goals;
		
		private string _stadium;
		
		private System.Nullable<int> _attendance;
		
		private string _home_club_name;
		
		private string _away_club_name;
		
		private System.Nullable<System.TimeSpan> _aggregate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ongame_idChanging(int value);
    partial void Ongame_idChanged();
    partial void Oncompetition_idChanging(string value);
    partial void Oncompetition_idChanged();
    partial void OnseasonChanging(int value);
    partial void OnseasonChanged();
    partial void OnroundChanging(string value);
    partial void OnroundChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    partial void Onhome_club_idChanging(System.Nullable<int> value);
    partial void Onhome_club_idChanged();
    partial void Onaway_club_idChanging(System.Nullable<int> value);
    partial void Onaway_club_idChanged();
    partial void Onhome_club_goalsChanging(System.Nullable<byte> value);
    partial void Onhome_club_goalsChanged();
    partial void Onaway_club_goalsChanging(System.Nullable<byte> value);
    partial void Onaway_club_goalsChanged();
    partial void OnstadiumChanging(string value);
    partial void OnstadiumChanged();
    partial void OnattendanceChanging(System.Nullable<int> value);
    partial void OnattendanceChanged();
    partial void Onhome_club_nameChanging(string value);
    partial void Onhome_club_nameChanged();
    partial void Onaway_club_nameChanging(string value);
    partial void Onaway_club_nameChanged();
    partial void OnaggregateChanging(System.Nullable<System.TimeSpan> value);
    partial void OnaggregateChanged();
    #endregion
		
		public SoccerGame()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_game_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int game_id
		{
			get
			{
				return this._game_id;
			}
			set
			{
				if ((this._game_id != value))
				{
					this.Ongame_idChanging(value);
					this.SendPropertyChanging();
					this._game_id = value;
					this.SendPropertyChanged("game_id");
					this.Ongame_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_competition_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string competition_id
		{
			get
			{
				return this._competition_id;
			}
			set
			{
				if ((this._competition_id != value))
				{
					this.Oncompetition_idChanging(value);
					this.SendPropertyChanging();
					this._competition_id = value;
					this.SendPropertyChanged("competition_id");
					this.Oncompetition_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_season", DbType="Int NOT NULL")]
		public int season
		{
			get
			{
				return this._season;
			}
			set
			{
				if ((this._season != value))
				{
					this.OnseasonChanging(value);
					this.SendPropertyChanging();
					this._season = value;
					this.SendPropertyChanged("season");
					this.OnseasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_round", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string round
		{
			get
			{
				return this._round;
			}
			set
			{
				if ((this._round != value))
				{
					this.OnroundChanging(value);
					this.SendPropertyChanging();
					this._round = value;
					this.SendPropertyChanged("round");
					this.OnroundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_club_id", DbType="Int")]
		public System.Nullable<int> home_club_id
		{
			get
			{
				return this._home_club_id;
			}
			set
			{
				if ((this._home_club_id != value))
				{
					this.Onhome_club_idChanging(value);
					this.SendPropertyChanging();
					this._home_club_id = value;
					this.SendPropertyChanged("home_club_id");
					this.Onhome_club_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_away_club_id", DbType="Int")]
		public System.Nullable<int> away_club_id
		{
			get
			{
				return this._away_club_id;
			}
			set
			{
				if ((this._away_club_id != value))
				{
					this.Onaway_club_idChanging(value);
					this.SendPropertyChanging();
					this._away_club_id = value;
					this.SendPropertyChanged("away_club_id");
					this.Onaway_club_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_club_goals", DbType="TinyInt")]
		public System.Nullable<byte> home_club_goals
		{
			get
			{
				return this._home_club_goals;
			}
			set
			{
				if ((this._home_club_goals != value))
				{
					this.Onhome_club_goalsChanging(value);
					this.SendPropertyChanging();
					this._home_club_goals = value;
					this.SendPropertyChanged("home_club_goals");
					this.Onhome_club_goalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_away_club_goals", DbType="TinyInt")]
		public System.Nullable<byte> away_club_goals
		{
			get
			{
				return this._away_club_goals;
			}
			set
			{
				if ((this._away_club_goals != value))
				{
					this.Onaway_club_goalsChanging(value);
					this.SendPropertyChanging();
					this._away_club_goals = value;
					this.SendPropertyChanged("away_club_goals");
					this.Onaway_club_goalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stadium", DbType="NVarChar(100)")]
		public string stadium
		{
			get
			{
				return this._stadium;
			}
			set
			{
				if ((this._stadium != value))
				{
					this.OnstadiumChanging(value);
					this.SendPropertyChanging();
					this._stadium = value;
					this.SendPropertyChanged("stadium");
					this.OnstadiumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attendance", DbType="Int")]
		public System.Nullable<int> attendance
		{
			get
			{
				return this._attendance;
			}
			set
			{
				if ((this._attendance != value))
				{
					this.OnattendanceChanging(value);
					this.SendPropertyChanging();
					this._attendance = value;
					this.SendPropertyChanged("attendance");
					this.OnattendanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_club_name", DbType="NVarChar(100)")]
		public string home_club_name
		{
			get
			{
				return this._home_club_name;
			}
			set
			{
				if ((this._home_club_name != value))
				{
					this.Onhome_club_nameChanging(value);
					this.SendPropertyChanging();
					this._home_club_name = value;
					this.SendPropertyChanged("home_club_name");
					this.Onhome_club_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_away_club_name", DbType="NVarChar(100)")]
		public string away_club_name
		{
			get
			{
				return this._away_club_name;
			}
			set
			{
				if ((this._away_club_name != value))
				{
					this.Onaway_club_nameChanging(value);
					this.SendPropertyChanging();
					this._away_club_name = value;
					this.SendPropertyChanged("away_club_name");
					this.Onaway_club_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aggregate", DbType="Time")]
		public System.Nullable<System.TimeSpan> aggregate
		{
			get
			{
				return this._aggregate;
			}
			set
			{
				if ((this._aggregate != value))
				{
					this.OnaggregateChanging(value);
					this.SendPropertyChanging();
					this._aggregate = value;
					this.SendPropertyChanged("aggregate");
					this.OnaggregateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SoccerPlayers")]
	public partial class SoccerPlayer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _player_id;
		
		private string _first_name;
		
		private string _last_name;
		
		private string _name;
		
		private System.Nullable<int> _last_season;
		
		private System.Nullable<int> _current_club_id;
		
		private string _player_code;
		
		private string _country_of_citizenship;
		
		private System.Nullable<System.DateTime> _date_of_birth;
		
		private string _sub_position;
		
		private string _position;
		
		private string _foot;
		
		private System.Nullable<int> _height_in_cm;
		
		private string _current_club_name;
		
		private System.Nullable<decimal> _market_value_in_eur;
		
		private System.Nullable<decimal> _highest_market_value_in_eur;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onplayer_idChanging(int value);
    partial void Onplayer_idChanged();
    partial void Onfirst_nameChanging(string value);
    partial void Onfirst_nameChanged();
    partial void Onlast_nameChanging(string value);
    partial void Onlast_nameChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onlast_seasonChanging(System.Nullable<int> value);
    partial void Onlast_seasonChanged();
    partial void Oncurrent_club_idChanging(System.Nullable<int> value);
    partial void Oncurrent_club_idChanged();
    partial void Onplayer_codeChanging(string value);
    partial void Onplayer_codeChanged();
    partial void Oncountry_of_citizenshipChanging(string value);
    partial void Oncountry_of_citizenshipChanged();
    partial void Ondate_of_birthChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_of_birthChanged();
    partial void Onsub_positionChanging(string value);
    partial void Onsub_positionChanged();
    partial void OnpositionChanging(string value);
    partial void OnpositionChanged();
    partial void OnfootChanging(string value);
    partial void OnfootChanged();
    partial void Onheight_in_cmChanging(System.Nullable<int> value);
    partial void Onheight_in_cmChanged();
    partial void Oncurrent_club_nameChanging(string value);
    partial void Oncurrent_club_nameChanged();
    partial void Onmarket_value_in_eurChanging(System.Nullable<decimal> value);
    partial void Onmarket_value_in_eurChanged();
    partial void Onhighest_market_value_in_eurChanging(System.Nullable<decimal> value);
    partial void Onhighest_market_value_in_eurChanged();
    #endregion
		
		public SoccerPlayer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_player_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int player_id
		{
			get
			{
				return this._player_id;
			}
			set
			{
				if ((this._player_id != value))
				{
					this.Onplayer_idChanging(value);
					this.SendPropertyChanging();
					this._player_id = value;
					this.SendPropertyChanged("player_id");
					this.Onplayer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="NVarChar(50)")]
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this.Onfirst_nameChanging(value);
					this.SendPropertyChanging();
					this._first_name = value;
					this.SendPropertyChanged("first_name");
					this.Onfirst_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="NVarChar(50)")]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this.Onlast_nameChanging(value);
					this.SendPropertyChanging();
					this._last_name = value;
					this.SendPropertyChanged("last_name");
					this.Onlast_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_season", DbType="Int")]
		public System.Nullable<int> last_season
		{
			get
			{
				return this._last_season;
			}
			set
			{
				if ((this._last_season != value))
				{
					this.Onlast_seasonChanging(value);
					this.SendPropertyChanging();
					this._last_season = value;
					this.SendPropertyChanged("last_season");
					this.Onlast_seasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_current_club_id", DbType="Int")]
		public System.Nullable<int> current_club_id
		{
			get
			{
				return this._current_club_id;
			}
			set
			{
				if ((this._current_club_id != value))
				{
					this.Oncurrent_club_idChanging(value);
					this.SendPropertyChanging();
					this._current_club_id = value;
					this.SendPropertyChanged("current_club_id");
					this.Oncurrent_club_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_player_code", DbType="NVarChar(50)")]
		public string player_code
		{
			get
			{
				return this._player_code;
			}
			set
			{
				if ((this._player_code != value))
				{
					this.Onplayer_codeChanging(value);
					this.SendPropertyChanging();
					this._player_code = value;
					this.SendPropertyChanged("player_code");
					this.Onplayer_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_of_citizenship", DbType="NVarChar(50)")]
		public string country_of_citizenship
		{
			get
			{
				return this._country_of_citizenship;
			}
			set
			{
				if ((this._country_of_citizenship != value))
				{
					this.Oncountry_of_citizenshipChanging(value);
					this.SendPropertyChanging();
					this._country_of_citizenship = value;
					this.SendPropertyChanged("country_of_citizenship");
					this.Oncountry_of_citizenshipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_birth", DbType="DateTime2")]
		public System.Nullable<System.DateTime> date_of_birth
		{
			get
			{
				return this._date_of_birth;
			}
			set
			{
				if ((this._date_of_birth != value))
				{
					this.Ondate_of_birthChanging(value);
					this.SendPropertyChanging();
					this._date_of_birth = value;
					this.SendPropertyChanged("date_of_birth");
					this.Ondate_of_birthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sub_position", DbType="NVarChar(50)")]
		public string sub_position
		{
			get
			{
				return this._sub_position;
			}
			set
			{
				if ((this._sub_position != value))
				{
					this.Onsub_positionChanging(value);
					this.SendPropertyChanging();
					this._sub_position = value;
					this.SendPropertyChanged("sub_position");
					this.Onsub_positionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="NVarChar(50)")]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this.OnpositionChanging(value);
					this.SendPropertyChanging();
					this._position = value;
					this.SendPropertyChanged("position");
					this.OnpositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foot", DbType="NVarChar(50)")]
		public string foot
		{
			get
			{
				return this._foot;
			}
			set
			{
				if ((this._foot != value))
				{
					this.OnfootChanging(value);
					this.SendPropertyChanging();
					this._foot = value;
					this.SendPropertyChanged("foot");
					this.OnfootChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_height_in_cm", DbType="Int")]
		public System.Nullable<int> height_in_cm
		{
			get
			{
				return this._height_in_cm;
			}
			set
			{
				if ((this._height_in_cm != value))
				{
					this.Onheight_in_cmChanging(value);
					this.SendPropertyChanging();
					this._height_in_cm = value;
					this.SendPropertyChanged("height_in_cm");
					this.Onheight_in_cmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_current_club_name", DbType="NVarChar(100)")]
		public string current_club_name
		{
			get
			{
				return this._current_club_name;
			}
			set
			{
				if ((this._current_club_name != value))
				{
					this.Oncurrent_club_nameChanging(value);
					this.SendPropertyChanging();
					this._current_club_name = value;
					this.SendPropertyChanged("current_club_name");
					this.Oncurrent_club_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_market_value_in_eur", DbType="Money")]
		public System.Nullable<decimal> market_value_in_eur
		{
			get
			{
				return this._market_value_in_eur;
			}
			set
			{
				if ((this._market_value_in_eur != value))
				{
					this.Onmarket_value_in_eurChanging(value);
					this.SendPropertyChanging();
					this._market_value_in_eur = value;
					this.SendPropertyChanged("market_value_in_eur");
					this.Onmarket_value_in_eurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_highest_market_value_in_eur", DbType="Money")]
		public System.Nullable<decimal> highest_market_value_in_eur
		{
			get
			{
				return this._highest_market_value_in_eur;
			}
			set
			{
				if ((this._highest_market_value_in_eur != value))
				{
					this.Onhighest_market_value_in_eurChanging(value);
					this.SendPropertyChanging();
					this._highest_market_value_in_eur = value;
					this.SendPropertyChanged("highest_market_value_in_eur");
					this.Onhighest_market_value_in_eurChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SoccerPlayersValuations")]
	public partial class SoccerPlayersValuation
	{
		
		private int _player_id;
		
		private System.DateTime _date;
		
		private int _market_value_in_eur;
		
		private int _current_club_id;
		
		private string _player_club_domestic_competition_id;
		
		public SoccerPlayersValuation()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_player_id", DbType="Int NOT NULL")]
		public int player_id
		{
			get
			{
				return this._player_id;
			}
			set
			{
				if ((this._player_id != value))
				{
					this._player_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_market_value_in_eur", DbType="Int NOT NULL")]
		public int market_value_in_eur
		{
			get
			{
				return this._market_value_in_eur;
			}
			set
			{
				if ((this._market_value_in_eur != value))
				{
					this._market_value_in_eur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_current_club_id", DbType="Int NOT NULL")]
		public int current_club_id
		{
			get
			{
				return this._current_club_id;
			}
			set
			{
				if ((this._current_club_id != value))
				{
					this._current_club_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_player_club_domestic_competition_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string player_club_domestic_competition_id
		{
			get
			{
				return this._player_club_domestic_competition_id;
			}
			set
			{
				if ((this._player_club_domestic_competition_id != value))
				{
					this._player_club_domestic_competition_id = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
